export const Paths = {
  HOME: "/home",
  OBSH: "/obsh",
  HOSTPITALS: "/hospitals",
  NETFLIX: "/netflix",
  BU_HIDE_AND_SEEK: "/bu-hide-and-seek",
  MEOW_FEDDER: "/meow-feeder",
  EAT_FOR_HEALTH: "/eat-for-health",
  FINANCIAL_DIARY: "/financial-diary",
  BU_OPEN_HOUSE: "/bu-open-house",
  FUTURE_TEMP: "/future-temp",
  EDUCATION : "/education",
  WISESIGHT : "/wisesight",
  ANOUSITH: "/anousith",
};
